### ISSUE TITLE
Can mobile numbers be detected?

### ISSUE THREAD

**Issue by daniel-rikowski** [floere/phony#116]
It looks like there is already a lot of work put into mobile number detection, but I can't make it work.

For example calling `CountryCodes#mobile?` delegates to a missing `Country#mobile?` method.

On the other hand I can see some "code fragments" hinting to mobile number detection.

Will this be implemented or am I using it wrong?

Thank you.

**Comment by floere** [comment]
Closing this – it's been open too long.

**Comment by halo** [comment]
> I made some very simple mobile detection https://github.com/mobino/phone_classifier

This is good and sad at the same time. Good because I'm going to use it now, sad, because it should really be a part of Phony. Phony is by far the best maintained library, so it would be sad if changes get lost when being backported to other gems.

Originally I hoped that [these variables](https://github.com/floere/phony/blob/e0d7591396f82484e19dd1f4f096c968adf7d72d/lib/phony/countries/austria.rb#L31) could be exposed to the outside world (via a module). So others could hook in there. But I might be a bit naive there, considering that there are so many edge-cases.
