### ISSUE TITLE
Generate plausible phone numbers for testing

### ISSUE THREAD

**Issue by v-tsvid** [floere/phony#266]
Hello and thanks for such useful gem!

I need to make some test data with FactoryGirl to test my app. Using standard Faker issues I cannot generate correct phone numbers to return 'true' from plausible? method. 

Is there a way to generate plausible phone numbers with your gem?

Thanks

**Comment by floere** [comment]
@v-tsvid Hi there! I am afraid not. At least it's not written for it. Can you give me an example of how you use Faker?

**Comment by v-tsvid** [comment]
I was using basic Faker::PhoneNumber methods:
Faker::PhoneNumber.phone_number
Faker::PhoneNumber.cell_phone

They does not generate plausible phone numbers but just formatted sequences of digits, spaces and other chars like ().-

Finally I had solved this problem with following code in my factory:
sequence(:phone, 9000000) { |n| "38093#{n}"}

38093XXXXXXX is plausible Ukrainian mobile phone so I just populate it. Yes, it's not very nice test data, but now it's only one way I found.

**Comment by floere** [comment]
@v-tsvid I'm glad you found a solution! :+1:  Note that if the Ukranian number rules get updated in Phony, you may get errors (just so you know if you update Phony, you may get errors because Phony knows better what Ukranian numbers are plausible and which aren't).
I'm closing this – but please reopen if you need to! :rocket:

**Comment by toobulkeh** [comment]
:+1: for a Phony/Faker crossover testing number.
