### ISSUE TITLE
Normalization does not do what I expect it to do

### ISSUE THREAD

**Issue by nathansamson** [floere/phony#270]
My Use case. All numbers entered will be NZ (mobile) nunbers
I expect my users (sometimes a user in this case might be another conputer) in any of the following formats (normalized number is 64225784367).

(in my examples I already stripped all spaces and extranous charachters
* 225784367 With missing country code (coming from a computer system only caring about NZ numbers, but humans by now are trained to enter it in this format as well, this, while technically the most wrong option, is the most popular option)
* 0225784367 Adding a 0, to show its a local number
* +64225784367, adding country and + prefix
* 0064225784367. adding country code and 00 prefix
* 64225784367 fully normalized number (coming from other system)

When I run the test cases on each format (plausbile? with or without specifying cc, normalize again with or without, and format (on previously formatted numbers)) I get weird results
Summary herre, full output below

* when I didn't specify  the country code in my input number (22578... and 022578...), and specified cc: I got the right normalization (correct), but plausible? said false (incorrect).
* When I did specify the country code (+6422578.., 006422578... and 6422578...) and specified cc: plausible returned true (correct), but normalize basically added the country code again in the normalized version, breaking the normalized versions.

Obviously I do not want to specify cc depending on whether the user entered it already, I expect the library to take care of this...
I can understand not doing the right thing on 225784367 as this is in no way to be known if you actually meant country code 225 (Ivory Coast) or actually meant a local number (although specifying cc would make for a good override), but I would expect all other numbers to be handled correctly as they have a clear indication what country to check for (assuming you use cc as option to tell the library its NZ)

Note that I had basically the same problem when I tried it on a belgium number, so the problem seems to be more widespread than NZ rules alone

~~~
225784367
------------------------------------------------------------
Plausible (CC 64)?: false
Plausibl?: false
Normalize (CC 64)?: 64225784367
Normalize?: 225784367
Format (CC 64)?: +64 22 578 4367
Format?: +225 78 43 67

64225784367
------------------------------------------------------------
Plausible (CC 64)?: true
Plausibl?: true
Normalize (CC 64)?: 6464225784367
Normalize?: 64225784367
Format (CC 64)?: +64 6 422 5784367
Format?: +64 22 578 4367

+64225784367
------------------------------------------------------------
Plausible (CC 64)?: true
Plausibl?: true
Normalize (CC 64)?: 6464225784367
Normalize?: 64225784367
Format (CC 64)?: +64 6 422 5784367
Format?: +64 22 578 4367

0064225784367
------------------------------------------------------------
Plausible (CC 64)?: true
Plausibl?: true
Normalize (CC 64)?: 64064225784367
Normalize?: 64225784367
Format (CC 64)?: +64 0 642 25784367
Format?: +64 22 578 4367

0225784367
------------------------------------------------------------
Plausible (CC 64)?: false
Plausibl?: false
Normalize (CC 64)?: 64225784367
Normalize?: 225784367
Format (CC 64)?: +64 22 578 4367
Format?: +225 78 43 67
~~~

and for the code

~~~
['225784367', '64225784367','+64225784367','0064225784367','0225784367'].each do |m|
   puts m
   puts '-' * 60

   puts "Plausible (CC 64)?: #{Phony.plausible?(m, cc: '64')}"
   puts "Plausibl?: #{Phony.plausible?(m)}"

   puts "Normalize (CC 64)?: #{Phony.normalize(m, cc: '64')}"
   puts "Normalize?: #{Phony.normalize(m)}"

   puts "Format (CC 64)?: #{Phony.format(Phony.normalize(m, cc: '64'))}"
   puts "Format?: #{Phony.format(Phony.normalize(m))}"

   puts ''
end
~~~

**Comment by floere** [comment]
Hi @nathansamson 

Thanks for the excellent issue entry! Thanks to the examples and your nice overview I was able to follow it well.

A few comments from me below…

> when I didn't specify the country code in my input number (22578... and 022578...), and specified cc: I got the right normalization (correct), but plausible? said false (incorrect).

That sounds good. The normalization is accidentally right (the chance for that happening is high, as for most countries it means stripping away non-numeric characters). And plausibility checks for Ivory Coast numbers, as you already describe.

> When I did specify the country code (+6422578.., 006422578... and 6422578...) and specified cc: plausible returned true (correct), but normalize basically added the country code again in the normalized version, breaking the normalized versions.

I understand this may be very confusing.
Here, the issue is that for both methods the `cc` option is not described, and for that, I am sorry. I've added an issue to follow this up here: #272.

For the `plausible?` method, the `cc` option makes it necessary that a number is plausible for a country. So if you pass in `'64'` it means that the number needs to be a NZ number to be plausible. So, for `22578…` numbers, it will return false, as Phony will not recognize it as a NZ number.

For the `normalize` method, the `cc` option means that you preselect a country. That means that instead of taking the first few digits of a number to determine what country it is from, it will just assume the cc you tell it is right.
This will only work with number without a CC. Why? (See below)

> Obviously I do not want to specify cc depending on whether the user entered it already, I expect the library to take care of this...

Many countries have NDCs that are equal to their CC, so Phony can't just chop off the start of a number given to get the number without CC, because it could erroneously chop off the NDC.

It sounds that in your case, it seems to be possible to add `64` to numbers coming from certain sources (or in a specific format, e.g. with a 0 added to indicate a non-CC number), and not to others to normalize the data in your data store (e.g. a database). Would that be a possibility?

**Comment by nathansamson** [comment]
> It sounds that in your case, it seems to be possible to add 64 to numbers coming from certain sources (or in a specific format, e.g. with a 0 added to indicate a non-CC number), and not to others to normalize the data in your data store (e.g. a database). Would that be a possibility?

That would definitly be a possibility, but would kind of defeat the point for us to use Phony at all sadly enough.

**Comment by floere** [comment]
I guess what I am thinking about is that if Phony does not want to chop off the CC because of the possible errors that could occur – you could do easily do that, knowing all the cases :)

Here's what I'd do:

```
require 'phony'

# List of cases.
numbers = %w[
  225784367
  64225784367
  +64225784367
  0064225784367
  0225784367
]

result = numbers.map do |number|
  # Cover all cases – prepend a 64 if none existed.
  number = number.sub(/^[0\+]*(64+|\b)/, '64')
  # Then normalize normally.
  Phony.normalize(number)
end

puts result

# Results in:
# 64225784367
# 64225784367
# 64225784367
# 64225784367
# 64225784367
```

Imho, you don't always need a lib to take care of everything (because, as I said, in this case, it's not possible). Cheers! :rocket:
