### ISSUE TITLE
Bosnia and Herzegovina number considered not plausible

### ISSUE THREAD

**Issue by DMA57361** [floere/phony#342]
What I did
----------

* `Phony.plausible? '+38766666666'`

What happened
-------------

* Returned `false`

What I expected to happen and why
---------------------------------

Return value `true`.

Saw another issue on here point to https://www.textmagic.com/free-tools/phone-validator and indicate the number works, so did the same and entered `066666666` for Bosnia and Herzegovina, it thinks this should be valid.

For what it's worth, I've noticed that  `Phony.plausible? '+387066666666'` _does return true_, but I'm pretty sure that the zero after the country code shouldn't be there? Sites like the above and so on seem to indicate the zero should be removed... maybe it's valid though?

Note, this isn't the number I originally had, but that belongs to a customer of ours so I'm not using it here. It's the same length, also begins with a 6 and returns the same results for all the checks I've described above.

**Comment by floere** [comment]
Hi Daniel

Thanks for the issue entry! 😊 The note is especially helpful.
Do you feel up to the task of improving this and providing a PR? (Some pointers: Bosnia is defined in `countries.rb`, and the `trunk` method takes an option, whose … options you can check in `TrunkCode`) I'm asking because my time is sadly very limited. But always happy to merge a PR 😊

Cheers
   Florian
