### ISSUE TITLE
Phony.normalize not detecting explicit cc

### ISSUE THREAD

**Issue by pudiva** [floere/phony#349]
What I did
----------

`Phony.normalize('+55 61 98788-9878', cc: '55')`
`Phony.normalize('+54 61 98788-9878', cc: '54')`
`Phony.normalize('+31 61 98788-9878', cc: '31')`
`Phony.normalize('+81 61 98788-9878', cc: '81')`
`Phony.normalize('+61 61 98788-9878', cc: '61')`

What happened
-------------

respectively:
`=> "555561987889878"`
`=> "545461987889878"`
`=> "313161987889878"`
`=> "818161987889878"`
`=> "616161987889878"`

What I expected to happen and why
---------------------------------

respectively:
`=> "5561987889878"`
`=> "5461987889878"`
`=> "3161987889878"`
`=> "8161987889878"`
`=> "6161987889878"`

or some invalid number error or documentation note. because teh country code seems quite explicit with teh '+'.

**Comment by ayghor** [comment]
`PhonyRails.normalize_number()` give teh results i expect

**Comment by edgibbs** [comment]
So based on the docs the following example returns the expected result with the 'US' which has a trunk code of '1':

`Phony.normalize('+1 724 999 9999', cc: '1').assert == '17249999999'`

The difference with say a 54 country code for Argentina is you get a duplicate which seems wrong: 

`Phony.normalize('+54 61 98788-9878', cc: '54').assert == '545461987889878'`

This appears to be a duplicate because the trunk_code is just looking for a leading 0 to strip off.

This doesn't happen with PhonyRails because they are do some parsing and pass the string '+5461987889878' in this case which ends up the with the expected normalization.

I don't have enough context to know if this is expected behavior, but if not I could look into a fix.

**Comment by ayghor** [comment]
> So based on the docs the following example returns the expected result with the 'US' which has a trunk code of '1':

yes, this does indeed work for me too
```
irb(main):005:0> Phony.normalize('+1 724 999 9999', cc: '1')
=> "17249999999"
```

> This appears to be a duplicate because the trunk_code is just looking for a leading 0 to strip off.
sry i didnt get it, you mean it expects 0 before anything to understand that 54 is country code?
```
irb(main):003:0> Phony.normalize('05461987889878', cc: '54')
=> "545461987889878"
```

> This doesn't happen with PhonyRails because they are do some parsing and pass the string '+5461987889878' in this case which ends up the with the expected normalization.

wat? i get duplicate with this too
```
irb(main):002:0> Phony.normalize('+5461987889878', cc: '54')
=> "545461987889878"
```

**Comment by edgibbs** [comment]
OK, so in the code it uses CountryCodes to determine what it might need to strip off in a trunk_code attribute.  For 54, 'Argentina' it only looks for a leading zero to strip off so it ignores the leading 54.  It then later tacks on the Country Code of '54' onto the front leading to the result you see:

```ruby
Phony.normalize('+54 61 98788-9878', cc: '54').assert == '545461987889878'`
```

PhonyRails uses Phony.normalize, but before it makes the call it has parsed the number to a more simplified form of '+5461987889878' and removed the country code.  Thus the call its making to Phony.normalize() returns the expected result:

```ruby
PhonyRails.normalize_number("+54 61 987889878", cc: '54').assert == '5461987889878'
```
Because the real call it ends up making to Phony.normalize() is the following:

```ruby
Phony.normalize("+5461987889878")
```

**Comment by ayghor** [comment]
oh yes, `Phony.normalize("+5461987889878")` does not duplicate '54', but also does not add it if it's missing.

btw this number looks plausible in brasil (55), idk about argentina (54) and teh others - were just lazy cc tests.
