### ISSUE TITLE
plausible? method returns false on numbers with cc (but normalize works)

### ISSUE THREAD

**Issue by callmeed** [floere/phony#382]
What I did
----------

* Tried to validate a number + cc using the `.plausible?` method before normalizing
```

irb> phone = '(310) 555-2121'
=> "(310) 555-2121"
irb> cc = '1'
=> "1"
irb> Phony.plausible?(phone, cc: cc)
=> false
irb> Phony.normalize(phone, cc: cc)
=> "13105552121"
```

What happened
-------------

* The `.plausible?` method returned `false` even though calling `normalize` works when specifying the cc.

What I expected to happen and why
---------------------------------

* The Normalize docs explicitly state to use `.plausible?` before normalizing
* It stands to reason that `.plausible?` should accept a cc param just like `normalize` and return the proper bool value

**Comment by floere** [comment]
Thanks for the nice writeup, Erik!

The issue here is that plausible? uses the cc parameter differently - it
reduces the possibility that a number is plausible to only the numbers
which have a certain cc. The first example in the plausible? docs shows
this.

I noticed that there should be an accompanying text explaining this more
clearly, sorry about that!

So you should be able to use both and not use the cc parameter with
plausible?. Does that help?

**Comment by dsgraham** [comment]
The `plausible?` method still doesn't do what one would expect. It seems to only return true if the phone number string includes the country code.

```
[8] pry(main)> Phony.plausible?('616-123-4574')
=> false
[9] pry(main)> Phony.plausible?('616-123-4574', cc: '1')
=> false
[10] pry(main)> Phony.plausible?('1-616-123-4574', cc: '1')
=> true
[11] pry(main)> Phony.plausible?('1-616-123-4574')
=> true
```

Shouldn't all of those return true?
