### ISSUE TITLE
Phony.plausible? returned true for random UUID

### ISSUE THREAD

**Issue by ream88** [floere/phony#400]
What I did
----------
I tried to check if `b496bab8-f99c-4f9b-bb8b-2d3e37fbd3fd` is a valid phone number.

What happened
-------------
```ruby
Phony.plausible?('b496bab8-f99c-4f9b-bb8b-2d3e37fbd3fd')
=> true
```

What I expected to happen and why
---------------------------------
It should return false, even if the given string happen to include a number. (It includes `49689949823373` which is a valid phone number)

**Comment by floere** [comment]
Thanks for the issue, @ream88!
I'm curious – what was the scenario where this came about?
I think it'd be hard to exclude all UUID, since a class of them are valid phone numbers. But we could exclude numbers which have non-numeric characters in the first N positions (I need to determine N). Does that sound good to you?

**Comment by ream88** [comment]
The problem is related to a http://twilio.com API, which allows you to create a call to a WebRTC client by calling `client:RANDOM_ID`. We now have the following check (pseudo code, not the real one):

```ruby
def valid?(number)
  if Phony.plausible?(number)
    # PSTN number
  else
    # client "number"
  end
end
```

I could of course change the check, however we didn't encounter the problem in production yet. Just happened to fail one of our fuzz tests.

**Comment by asilano** [comment]
Related, and encountered through joost/phony_rails#204 - `https://example.com/15.55/a5b5c5/rse5.555` is considered plausible.

We encounter this in a database field designed to provide a Call To Action - that is, a suggested next point of contact - which we permit to be a phone number or URL.

I can see the attraction of being able to normalize `"John: +1 555 555-555"`, but the false positives are annoying.

**Comment by floere** [comment]
@asilano I'm open to constructive suggestions. Plausible really tries to find anything phone numbery out of a noisy string. An idea would be a more restrictive ?-method, which only ignores `+-.`.

However, in your case, as URLs are relatively constricted compared to phone numbers, why do you not check if it's a feasible URL first instead of the other way round?

**Comment by asilano** [comment]
<img src='https://user-images.githubusercontent.com/1043824/108727440-807cd500-7520-11eb-964a-26e42c9bbaf5.png' width=200>

You make a good point. I thought we allowed internal URLs (which would be harder to spot - no scheme) but I think here we don't.
